language: node_js
node_js: "11"
addons:
  chrome: stable
sudo: required
before_script:
  -
script:
  - npm test
  - npm run build
after_success:
  - git init
  - git config --global user.name 'superman285'
  - git config --global user.email 'superman285@126.com'
  - git add .
  - git commit -m "rebuild TicTacToe project,update the dist directory"
  - git push --force "https://${GITHUB_TOKEN}@${GITHUB_REPO}" master

env:
  global:
    - GITHUB_REPO: github.com/superman285/TicTacToe.git